server:
  port: 8081
#FreeMarker
pring:
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
spring:
    datasource:
       name: ssm
       url: jdbc:mysql://192.168.0.101:3306/ssm?useUnicode=true&characterEncoding=utf8
       username: root
       password: root
       # 使用druid数据源
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.cj.jdbc.Driver
       #com.mysql.jdbc.Driver
       filters: stat
       maxActive: 20
       initialSize: 1
       maxWait: 60000
       minIdle: 1
       timeBetweenEvictionRunsMillis: 60000
       minEvictableIdleTimeMillis: 300000
       validationQuery: select 'x'
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false
       poolPreparedStatements: true
       maxOpenPreparedStatements: 20

    servlet:
        multipart:
           enabled: true
           max-file-size: 20MB
           max-request-size: 200MB


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.library


#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


##上传图片保存的路径
#img:
#  location: /Downloads/imgUpload/

#配置上传文件的最大值
servlet:
  multipart:
    max-file-size: 50Mb
    max-request-size: 50Mb



#自定义文件上传路径
web:
  upload-path: /Downloads/imgUpload/









